---
- hosts: java
  become: true
  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
      become: yes
      tags:
        - prometheus

    - name: Ensure Prometheus service is enabled and started
      systemd:
        name: prometheus
        state: started
        enabled: yes
      become: yes
      tags:
        - prometheus
