pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                sh 'rm -rf bus_booking'
                sh 'git clone https://github.com/yatheesh2328/bus_booking.git'
            }
        }

        stage('build') {
            steps {
                    sh 'mvn --version'
                    sh 'mvn clean install'
                }
            }
        stage('Run JAR locally')
        steps {
            sh '
        stage('Sonarqube Scan') {
            steps {
            withSonarQubeEnv('sonar'){
                script {
                    sonar()
                }
            }
            }
        }
    }
}
