pipeline{
  agent {label 'slave1'
         stages{
           stage('checkout stage'){
             steps{
               sh. 'ansible-playbook sample.yml'
             }
           }
         }
        }
}
